apiVersion: v1
kind: Service
metadata:
  name: productreview-svc
  namespace: shoppingportal
  labels:
    app: productreview-svc
spec:
  selector:
    app: productreview-svc
  type: ClusterIP
  ports:
   - port: 80
     targetPort: 8080
     name: http